#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/finkel/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/finkel/.local/share/pnpm/global/5/.pnpm/node_modules"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../.local/share/pnpm/global/5/node_modules/openapi2schema/index.js" "$@"
else
  exec node  "$basedir/../../../../../../.local/share/pnpm/global/5/node_modules/openapi2schema/index.js" "$@"
fi
