FROM eclipse-temurin:21-jre

RUN apt-get update && \
      apt-get install -y curl && \
  rm -rf /var/lib/apt/lists/*

# install the app
COPY   target/app.jar   /app/app.jar

ENTRYPOINT ["java","-jar","/app/app.jar"]
